In [17]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 15)
np.random.seed(5)

import warnings
warnings.filterwarnings('ignore')

np.random.seed(5)
sns.set()

In [18]:
from google.colab import drive
drive.mount('/content/drive')
final_index_batter = pd.read_csv('/content/drive/MyDrive/Diss/Code/CSV/Results/final_training_evaluation_batter.csv')
final_index_batter_test = pd.read_csv('/content/drive/MyDrive/Diss/Code/CSV/Results/final_test_evaluation_batter.csv')
final_index_bowling = pd.read_csv('/content/drive/MyDrive/Diss/Code/CSV/Results/final_training_evaluation_bowler.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
top10AllTime_allRounders = {'SR Watson':1,'Shahid Afridi':2,'Shakib Al Hasan':3,'GJ Maxwell':4,'Yuvraj Singh':5,'ST Jayasuriya':6,'Mohammad Nabi':7,'DJ Hussey':8,'MN Samuels':9,'CH Gayle':10}

In [20]:
top10_batters = final_index_batter[final_index_batter.name.isin(top10AllTime_allRounders.keys())].copy()
top10_batters = top10_batters.append(final_index_batter_test[final_index_batter_test.name.isin(top10AllTime_allRounders.keys())].copy())
top10_bowlers = final_index_bowling[final_index_bowling.name.isin(top10AllTime_allRounders.keys())].copy()

In [21]:
top10_batters.sort_values('name',inplace=True)
top10_bowlers.sort_values('name',inplace=True)

In [22]:
top10_batters['hussey_index(bat)'] = top10_batters['average'] + top10_batters['strike_rate']
top10_batters

,name,country,average,strike_rate,boundary_per_ball,boundary_index,finishing_index,runs_without_boundary_index,big_match_index,prelim_metric,pre-rank,kmeans_role,rbml_score,pca_score,hussey_index(bat)
18,CH Gayle,WI,27.92,137.50,0.204,3.760,0.093,6.973,0.240,38.390,Best,SB,1.262,2.952,165.42
106,DJ Hussey,AUS,22.90,121.34,0.120,2.083,0.083,10.778,0.083,27.787,Good,FL,0.349,1.018,144.24
4,GJ Maxwell,AUS,30.96,154.00,0.203,3.390,0.169,9.662,0.195,47.678,Best,SB,1.427,3.483,184.96
33,MN Samuels,WI,29.29,116.23,0.154,3.277,0.154,9.554,0.154,34.044,Best,FL,0.817,2.050,145.52
36,Mohammad Nabi,AFG,22.97,142.23,0.174,2.321,0.173,7.617,0.049,32.670,Best,FL,0.362,1.237,165.20
44,SR Watson,AUS,29.24,145.32,0.197,3.536,0.107,9.000,0.214,42.492,Best,SB,1.244,3.058,174.56
139,ST Jayasuriya,SL,23.29,129.15,0.203,3.300,0.100,6.233,0.133,30.079,Best,FL,0.588,1.919,152.44
48,Shahid Afridi,PAK,17.92,150.00,0.186,1.934,0.132,6.220,0.044,26.880,Good,F,0.394,0.923,167.92
17,Shakib Al Hasan,BAN,22.44,119.77,0.145,2.432,0.105,9.558,0.095,26.876,Good,FL,0.408,1.197,142.21
62,Yuvraj Singh,INDIA,28.02,136.38,0.175,2.961,0.176,8.333,0.157,38.214,Best,FL,0.754,2.162,164.40

In [23]:
from pathlib import Path

In [24]:
filepath_batter_icc = Path('ICC_allTime_top_10_ar_batting.csv') 
top10_batters.sort_values('name').to_csv(filepath_batter_icc,index=False)

In [25]:
filepath_bowler_icc = Path('ICC_allTime_top_10_ar_bowling.csv') 
top10_bowlers.sort_values('name').to_csv(filepath_bowler_icc,index=False)

##### Downlaoded both the files for Batter and Bowler with the top 10 ICC All time All rounder.

##### Importing Top 10 ICC All time All rounder after pre processing in Excel.

In [26]:
top10_ICC_AR = pd.read_csv('/content/drive/MyDrive/Diss/Code/CSV/preProcesing_allRounder/ICC_top10_allrounders.csv')
top10_ICC_AR['ICC_rank'] = top10_ICC_AR.name.apply(lambda x: top10AllTime_allRounders.get(x))

In [27]:
top10_ICC_AR

,name,country,batting_pre_rank,bowling_pre_rank,batting_role,bowling_role,combined_rbml_Score,combined_pca_score,hussey_index(bat),ICC_rank
0,CH Gayle,WI,Best,Good,SB,LCB,1.729,3.736,165.42,10
1,DJ Hussey,AUS,Good,Good,FL,SPB,0.951,1.911,144.24,8
2,GJ Maxwell,AUS,Best,Good,SB,LCB,1.895,4.268,184.96,4
3,MN Samuels,WI,Best,Good,FL,SPB,1.382,2.977,145.52,9
4,Mohammad Nabi,AFG,Best,Good,FL,IB,1.004,2.352,165.20,7
5,SR Watson,AUS,Best,Good,SB,IB,1.892,4.216,174.56,1
6,ST Jayasuriya,SL,Best,Good,FL,SPB,1.172,2.861,152.44,6
7,Shahid Afridi,PAK,Good,Best,F,SB,0.992,2.208,167.92,2
8,Shakib Al Hasan,BAN,Good,Best,FL,SB,1.054,2.591,142.21,3
9,Yuvraj Singh,INDIA,Best,Best,FL,SPB,1.354,3.097,164.40,5

In [28]:
top10_ICC_AR['RBML_rank'] = top10_ICC_AR['combined_rbml_Score'].rank(method='max',numeric_only=True,ascending=False)
top10_ICC_AR['PCA_rank'] = top10_ICC_AR['combined_pca_score'].rank(method='max',numeric_only=True,ascending=False)
top10_ICC_AR['hussey_rank'] = top10_ICC_AR['hussey_index(bat)'].rank(method='max',numeric_only=True,ascending=False)
top10_ICC_AR

,name,country,batting_pre_rank,bowling_pre_rank,batting_role,bowling_role,combined_rbml_Score,combined_pca_score,hussey_index(bat),ICC_rank,RBML_rank,PCA_rank,hussey_rank
0,CH Gayle,WI,Best,Good,SB,LCB,1.729,3.736,165.42,10,3.0,3.0,4.0
1,DJ Hussey,AUS,Good,Good,FL,SPB,0.951,1.911,144.24,8,10.0,10.0,9.0
2,GJ Maxwell,AUS,Best,Good,SB,LCB,1.895,4.268,184.96,4,1.0,1.0,1.0
3,MN Samuels,WI,Best,Good,FL,SPB,1.382,2.977,145.52,9,4.0,5.0,8.0
4,Mohammad Nabi,AFG,Best,Good,FL,IB,1.004,2.352,165.20,7,8.0,8.0,5.0
5,SR Watson,AUS,Best,Good,SB,IB,1.892,4.216,174.56,1,2.0,2.0,2.0
6,ST Jayasuriya,SL,Best,Good,FL,SPB,1.172,2.861,152.44,6,6.0,6.0,7.0
7,Shahid Afridi,PAK,Good,Best,F,SB,0.992,2.208,167.92,2,9.0,9.0,3.0
8,Shakib Al Hasan,BAN,Good,Best,FL,SB,1.054,2.591,142.21,3,7.0,7.0,10.0
9,Yuvraj Singh,INDIA,Best,Best,FL,SPB,1.354,3.097,164.40,5,5.0,4.0,6.0

In [29]:
convert_dtypes = {'RBML_rank':int,'PCA_rank':int,'hussey_rank':int}
top10_ICC_AR=top10_ICC_AR.astype(convert_dtypes)

In [30]:
cols = top10_ICC_AR.columns.tolist()
cols = ['ICC_rank','name','country','batting_pre_rank','bowling_pre_rank','batting_role','bowling_role','combined_rbml_Score','RBML_rank','combined_pca_score','PCA_rank','hussey_index(bat)','hussey_rank']
top10_ICC_AR = top10_ICC_AR[cols]

In [31]:
top10_ICC_AR.sort_values('ICC_rank')

,ICC_rank,name,country,batting_pre_rank,bowling_pre_rank,batting_role,bowling_role,combined_rbml_Score,RBML_rank,combined_pca_score,PCA_rank,hussey_index(bat),hussey_rank
5,1,SR Watson,AUS,Best,Good,SB,IB,1.892,2,4.216,2,174.56,2
7,2,Shahid Afridi,PAK,Good,Best,F,SB,0.992,9,2.208,9,167.92,3
8,3,Shakib Al Hasan,BAN,Good,Best,FL,SB,1.054,7,2.591,7,142.21,10
2,4,GJ Maxwell,AUS,Best,Good,SB,LCB,1.895,1,4.268,1,184.96,1
9,5,Yuvraj Singh,INDIA,Best,Best,FL,SPB,1.354,5,3.097,4,164.40,6
6,6,ST Jayasuriya,SL,Best,Good,FL,SPB,1.172,6,2.861,6,152.44,7
4,7,Mohammad Nabi,AFG,Best,Good,FL,IB,1.004,8,2.352,8,165.20,5
1,8,DJ Hussey,AUS,Good,Good,FL,SPB,0.951,10,1.911,10,144.24,9
3,9,MN Samuels,WI,Best,Good,FL,SPB,1.382,4,2.977,5,145.52,8
0,10,CH Gayle,WI,Best,Good,SB,LCB,1.729,3,3.736,3,165.42,4

In [32]:
filepath_allrounder_icc = Path('ICC_allTime_top_10_allRounder.csv') 
top10_ICC_AR.sort_values('ICC_rank').to_csv(filepath_allrounder_icc,index=False)